#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/opencode"

chown -R "$app:$app" "$install_dir"

ynh_script_progression "Initializing auth.json..."

write_auth_json

ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="OpenCode AI coding agent web interface" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

ynh_script_progression "Installation of $app completed"
