#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".local"

chown -R "$app:$app" "$install_dir"

ynh_script_progression "Re-starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

ynh_script_progression "Upgrade of $app completed"
