#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

mv --force "$install_dir/opencode" "/usr/local/bin/opencode"
chown root:root /usr/local/bin/opencode
chmod o+x /usr/local/bin/opencode
ynh_exec_as_app mkdir -p "$install_dir/.local/share/"
ynh_exec_as_app ln --symbolic --force "/usr/local/bin/opencode" "$install_dir/opencode"
ynh_exec_as_app ln --symbolic --force "$data_dir/.local/share/opencode" "$install_dir/.local/share/opencode"

ynh_script_progression "Re-starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

ynh_script_progression "Upgrade of $app completed"
